apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  username: dGVv
  password: d0gyN3NLN2c=
  database: Y2xpZW50cw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-con-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: con
  template:
    metadata:
      labels:
        app: con
    spec:
      containers:
      - name: gcp-con
        image: spiridon26/gcp-con:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: INSTANCE_HOST
          value: "10.128.0.8"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: database